### ISSUE TITLE
部署完成后,提示"提交的数据不合法"

### ISSUE THREAD

**Issue by hunhun010164** [ilyydy/cf-openai#34]
完成后,打开网页,提示"提交的数据不合法",且微信公众号里无论开启服务器还是停止服务器,一样的报错,麻烦看一下,谢谢

**Comment by ilyydy** [comment]
你用的哪种部署方式？这个错误可能的原因有好几种，还需要日志进一步确定。
你可以在 cloudflare 开启日志流，然后给公众号发消息，把日志发给我。也可以部署最新版本 0.4.2，开启 DEBUG_MODE并且建一个企业微信群机器人配置到告警 URL。这样所有日志都会发到企业微信群。


![屏幕截图 2023-08-10 230725](https://github.com/ilyydy/cf-openai/assets/8614566/61740949-f0ce-43b8-8bab-66902d5af107)

**Comment by hunhun010164** [comment]
> 你用的哪种部署方式？这个错误可能的原因有好几种，还需要日志进一步确定。 你可以在 cloudflare 开启日志流，然后给公众号发消息，把日志发给我。也可以部署最新版本 0.4.2，开启 DEBUG_MODE并且建一个企业微信群机器人配置到告警 URL。这样所有日志都会发到企业微信群。
> 
> ![屏幕截图 2023-08-10 230725](https://user-images.githubusercontent.com/8614566/259787258-61740949-f0ce-43b8-8bab-66902d5af107.png)

谢谢.域名和ID改了下,其他没动

OK	GET	https://mydomain/openai/wechat/test	8/11/2023 11:38:57AM

{
  "outcome": "ok",
  "scriptName": "hello-world-long-mountain-c56b",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [],
  "eventTimestamp": 1691717937264,
  "event": {
    "request": {
      "url": "https://mydomain/openai/wechat/test",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.9",
        "cache-control": "max-age=0",
        "cf-connecting-ip": "60.242.21.22",
        "cf-ipcountry": "AU",
        "cf-ray": "7f4cc313dc79a819",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "mydomain",
        "sec-ch-ua": "\"Chromium\";v=\"112\", \"Google Chrome\";v=\"112\", \"Not:A-Brand\";v=\"99\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "60.242.21.22"
      },
      "cf": {
        "clientTcpRtt": 5,
        "longitude": "151.20060",
        "latitude": "-33.87150",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "OC",
        "asn": 7545,
        "clientAcceptEncoding": "gzip, deflate, br",
        "country": "AU",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "62dbd94f0d884fa865c60f2a52b5c7bd413c7468361841c970c63d99cd9b195f",
          "clientHandshake": "175579e21e2d0b51ea6d8c7f96fa43bc181348b2f493d312ff558efb183d8843",
          "serverHandshake": "1c39bec9a5a7424fc170754319e8aac6353b78c3732339ba71889d68fb79170b",
          "serverFinished": "d497756f13bce0adf86bb43fd33c941f07b90c02f098f98d164bb890cb2306c1"
        },
        "tlsVersion": "TLSv1.3",
        "colo": "SYD",
        "timezone": "Australia/Sydney",
        "city": "Sydney",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=256;exclusive=1",
        "httpProtocol": "HTTP/2",
        "region": "New South Wales",
        "regionCode": "NSW",
        "asOrganization": "TPG Internet",
        "postalCode": "2000"
      }
    },
    "response": {
      "status": 200
    }
  },
  "id": 1
}

**Comment by hunhun010164** [comment]
我是用cloudflare的方式部署的.
我之前部署的0.4.1.现在部署0.4.2,是不是只要替换index.mini.js里的内容到cloudflare上即可?另外,如何开启DEBUG_MODE呢?请赐教,谢谢

**Comment by ilyydy** [comment]
感觉你好像用错了。我这个服务是没有网页的，你说的打开网页是这个链接吗？如果正常部署，在浏览器打开这个链接会显示当前时间

![屏幕截图 2023-08-11 232508](https://github.com/ilyydy/cf-openai/assets/8614566/358b268a-deb2-43f8-bcc3-db751c6b9cc0)

![屏幕截图 2023-08-11 232728](https://github.com/ilyydy/cf-openai/assets/8614566/d2419ace-8cea-4a4f-a905-a38d0eabadc4)

**Comment by ilyydy** [comment]
> 我是用cloudflare的方式部署的. 我之前部署的0.4.1.现在部署0.4.2,是不是只要替换index.mini.js里的内容到cloudflare上即可?另外,如何开启DEBUG_MODE呢?请赐教,谢谢

对，复制替换就可以

![屏幕截图 2023-08-11 233215](https://github.com/ilyydy/cf-openai/assets/8614566/11315ae0-9682-4e9c-9885-4021d372f492)

**Comment by hunhun010164** [comment]
> 感觉你好像用错了。我这个服务是没有网页的，你说的打开网页是这个链接吗？如果正常部署，在浏览器打开这个链接会显示当前时间
> 
> ![屏幕截图 2023-08-11 232508](https://user-images.githubusercontent.com/8614566/260048667-358b268a-deb2-43f8-bcc3-db751c6b9cc0.png)
> 
> ![屏幕截图 2023-08-11 232728](https://user-images.githubusercontent.com/8614566/260049188-d2419ace-8cea-4a4f-a905-a38d0eabadc4.png)

对,如果浏览器只是打开https://mydomain/
是显示当前时间的:
2023-08-12T01:07:08.821Z hello world

我如果用浏览器打开https://mydomain/openai/wechat/test
才显示"提交的数据不合法",莫非部署已经成功了?是我使用的姿势不对?还请赐教,谢谢

**Comment by ilyydy** [comment]
> > 感觉你好像用错了。我这个服务是没有网页的，你说的打开网页是这个链接吗？如果正常部署，在浏览器打开这个链接会显示当前时间
> > ![屏幕截图 2023-08-11 232508](https://user-images.githubusercontent.com/8614566/260048667-358b268a-deb2-43f8-bcc3-db751c6b9cc0.png)
> > ![屏幕截图 2023-08-11 232728](https://user-images.githubusercontent.com/8614566/260049188-d2419ace-8cea-4a4f-a905-a38d0eabadc4.png)
> 
> 对,如果浏览器只是打开https://mydomain/ 是显示当前时间的: 2023-08-12T01:07:08.821Z hello world
> 
> 我如果用浏览器打开https://mydomain/openai/wechat/test 才显示"提交的数据不合法",莫非部署已经成功了?是我使用的姿势不对?还请赐教,谢谢

那说明你已经把服务部署好了。浏览器打开https://mydomain/openai/wechat/test 是没用的，这个地址不是给浏览器用的。你要在微信里给绑定的微信公众号发消息，比如发 /help

**Comment by ilyydy** [comment]
发 /help 效果是这样

![IMG_20230812_093632](https://github.com/ilyydy/cf-openai/assets/8614566/daf805bc-b8ed-427c-b5be-0c2c5c6349ba)

**Comment by hunhun010164** [comment]
> 发 /help 效果是这样
> 
> ![IMG_20230812_093632](https://user-images.githubusercontent.com/8614566/260180658-daf805bc-b8ed-427c-b5be-0c2c5c6349ba.jpg)


谢谢,试了试,help指令正常
![help](https://github.com/ilyydy/cf-openai/assets/26036173/d1c91ddd-0a5b-4d8d-ade3-98e7cc1dafbc)

但其他指令貌似不能识别,麻烦看一下,谢谢
![chat](https://github.com/ilyydy/cf-openai/assets/26036173/6f533c59-71d3-42b1-95d6-17cf5f8da779)

**Comment by ilyydy** [comment]
> > 发 /help 效果是这样
> > ![IMG_20230812_093632](https://user-images.githubusercontent.com/8614566/260180658-daf805bc-b8ed-427c-b5be-0c2c5c6349ba.jpg)
> 
> 谢谢,试了试,help指令正常 ![help](https://user-images.githubusercontent.com/26036173/260272329-d1c91ddd-0a5b-4d8d-ade3-98e7cc1dafbc.jpg)
> 
> 但其他指令貌似不能识别,麻烦看一下,谢谢 ![chat](https://user-images.githubusercontent.com/26036173/260272359-6f533c59-71d3-42b1-95d6-17cf5f8da779.jpg)

有试过 /testkey 这个命令吗，看 openai key 配置好没有

**Comment by hunhun010164** [comment]
试了下,收到回复:
正在处理中，请稍后输入 .. 或以下命令获取回答
/retry 24222470899430138

**Comment by ilyydy** [comment]
> 试了下,收到回复: 正在处理中，请稍后输入 .. 或以下命令获取回答 /retry 24222470899430138

很奇怪，看起来都超时了。没有日志不太好确定哪一步慢了。你抓一下 /testkey 的日志看看

**Comment by hunhun010164** [comment]
发送/testkey后,出来3个日志,先是ExceededCpu,5秒后是Canceled,再过5秒后是OK.详见附件.谢谢

**Comment by ilyydy** [comment]
@hunhun010164 有2个问题
1. 你的 openai key 有问题用不了，调用 openai 接口失败 {\"message\":\"You exceeded your current quota, please check your plan and billing details.\",\"type\":\"insufficient_quota\",\"param\":null,\"code\":\"insufficient_quota\"}。
> 因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。，
https://github.com/Bin-Huang/chatbox/issues/717#issuecomment-1587209249
2. 你需要再更新一下最新版本，之前加的告警有点问题，会导致ExceededCpu
